ChangesMadeToGetCompilingInVisualStudio2013
# niflib
Git clone of niflib.
enum.h:
enum for SkyrimHavokMaterial turned into  : unsigned int enum (to fix
out of int range error)
enum for BSShaderFlags changed into unsigned int enum
enum for SkyrimShaderPropertyFlags2
enum for SkyrimShaderPropertyFlags1 changed into unsigned int enum (to
fix out of int range error)

nif_math.h:
<cstdint> include added to fix error:"uint16_t" is undefined

nifqhull.cpp:
byte definition changed :
Using byte =  unsigned char
(commented out typedef definition since Visual Studio 2013 intellesence
has having problems with redefinition of Byte dispute #ifndef block)

CodeStructure changes from VisualStudio2015 to VisualStudio2013 visual
studio project:
Now makes references to qhull within Solution
Qhull included now
(Since requires QHull and QHull licease requires link.:Changes made to
some QHull project files in order to generate qhull lib in correct
folder;Source can be override if qhull updates just keep the 4 project
files included the same/keep the changes other than extra
source/includes  )

Most changes in Visual Studio 2013 visual studio project assume
directory structure of:
(Assumes using 64 bit build--32 Bit build not tested)(Assumes using
Visual Studio 2013 Professional)
SolutionFolder
-GlobalCode
-niflib
-qhull
-ProjectUsingNiflib
-StaticLibraries
-qhull.lib
-niflib_static_x64.lib
-x64
-v120
-Niflib .obj files generated by Niflib(used during ProjectUsingNiflib
for linking)